### ISSUE TITLE
Data Filter

### ISSUE THREAD

**Issue by alkuku** [radorb/SIebookFall2016#1]
Still looking to a way to filter the section when you choose a chapter

**Comment by radorb** [comment]
Take a look and see if this helps.

[sql.txt](https://github.com/radorb/SIebookFall2016/files/504767/sql.txt)

**Comment by alkuku** [comment]
It didn't , my buddy 
with me trying to help

**Comment by alkuku** [comment]
I need help on php code to store the value of selected item from the chapter drop down list , so I can display other sections and links accordingly . I am stuck with storing the value of selected item from chapter drop down into a variable on this php page . If you can help me with this code , I can query the sections and links

**Comment by radorb** [comment]
I found this and it works. Just need to add a third drop down list for the edit links page. (select chapter, select section, select link)

http://www.plus2net.com/php_tutorial/php_drop_down_list.php
